
import React, { useEffect, useState } from 'react';
import { Users as UsersIcon, Shield, Lock, Loader2, Plus, X, Save } from 'lucide-react';
import { User, UserRole } from '../types';
import { supabase } from '../services/supabase';
import { sanitizePayload } from '../services/utils';

const Users: React.FC = () => {
  const [users, setUsers] = useState<User[]>([]);
  const [loading, setLoading] = useState(true);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [formData, setFormData] = useState({
    nick: '',
    password: '',
    role: UserRole.EMPLOYEE,
    full_name: ''
  });

  useEffect(() => {
    fetchUsers();
  }, []);

  const fetchUsers = async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase.from('users').select('*').order('created_at');
      if (error) throw error;
      setUsers(data || []);
    } catch (error) {
      console.error('Error fetching users', error);
    } finally {
      setLoading(false);
    }
  };

  const handleCreateUser = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      // Note: In a real Auth system, we would use supabase.auth.signUp
      // But since we are using custom auth table and simulation, we insert directly.
      // The 'password_hash' needs to be generated by Edge Function in real scenario.
      // Here we assume the database trigger or backend handles hashing, OR we send to Edge Function.
      
      // For this custom implementation, we will mock the hash or insert plain (NOT SECURE for prod without Edge Function hashing)
      // BUT, since we have the 'update_own_password' RPC, we can create the user then set password?
      // Better: We just insert into 'users' and let the backend logic handle it (or Edge Function).
      
      // Calling a hypothetical edge function to create user safely would be best.
      // For now, inserting directly to table for the "Custom Auth" simulation flow.
      
      const payload = sanitizePayload({
        nick: formData.nick,
        role: formData.role,
        full_name: formData.full_name,
        // In a real app, NEVER save plain text. This is for the simulation compatibility.
        // The SQL schema expects 'password_hash'.
        password_hash: '$2a$10$MockHashForDemoOnly' + Math.random() 
      });

      const { data, error } = await supabase.from('users').insert(payload).select().single();
      if (error) throw error;

      alert(`Usuário ${formData.nick} criado! (Senha inicial simulada)`);
      setUsers([...users, data]);
      setIsModalOpen(false);
      setFormData({ nick: '', password: '', role: UserRole.EMPLOYEE, full_name: '' });

    } catch (error: any) {
      console.error(error);
      alert(`Erro ao criar usuário: ${error.message}`);
    }
  };

  return (
    <div className="p-8 space-y-6 h-full overflow-y-auto">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold text-slate-800 flex items-center gap-2">
            <UsersIcon className="text-purple-600" /> Controle de Acesso
          </h2>
          <p className="text-slate-500">Gerencie usuários, roles e permissões do sistema.</p>
        </div>
        <button 
            onClick={() => setIsModalOpen(true)}
            className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 shadow-md flex items-center gap-2"
        >
          <Shield size={16} /> Novo Usuário
        </button>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
        {loading ? (
             <div className="flex justify-center p-12"><Loader2 className="animate-spin text-purple-600" /></div>
        ) : (
        <table className="w-full text-sm text-left">
          <thead className="bg-slate-50 text-slate-500 font-medium">
            <tr>
              <th className="px-6 py-4">Nome / Nickname</th>
              <th className="px-6 py-4">Nível de Acesso</th>
              <th className="px-6 py-4">Criado em</th>
              <th className="px-6 py-4 text-right">Ações</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {users.map((u) => (
              <tr key={u.id} className="hover:bg-slate-50">
                <td className="px-6 py-4">
                    <div className="font-bold text-slate-700">{u.nick}</div>
                    <div className="text-xs text-slate-500">{u.full_name}</div>
                </td>
                <td className="px-6 py-4">
                  <span className={`px-2 py-1 rounded text-xs font-bold uppercase ${
                    u.role === UserRole.MASTER ? 'bg-slate-900 text-white' : 
                    u.role === UserRole.ADMIN ? 'bg-purple-100 text-purple-700' : 
                    'bg-blue-100 text-blue-700'
                  }`}>
                    {u.role}
                  </span>
                </td>
                <td className="px-6 py-4 text-slate-500">
                  {new Date(u.created_at).toLocaleDateString('pt-BR')}
                </td>
                <td className="px-6 py-4 text-right">
                  <button className="text-slate-400 hover:text-blue-600 p-1" title="Bloqueado na Demo">
                    <Lock size={16} />
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        )}
      </div>
      
      {/* Modal Create User */}
      {isModalOpen && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-xl shadow-xl w-full max-w-md">
            <div className="p-6 border-b border-slate-100 flex justify-between items-center">
              <h3 className="text-lg font-bold text-slate-800">Novo Usuário</h3>
              <button onClick={() => setIsModalOpen(false)} className="text-slate-400 hover:text-slate-600"><X size={20} /></button>
            </div>
            <form onSubmit={handleCreateUser} className="p-6 space-y-4">
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Nome Completo</label>
                    <input type="text" required className="w-full p-2 border rounded bg-white" value={formData.full_name} onChange={e => setFormData({...formData, full_name: e.target.value})} />
                </div>
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Nickname (Login)</label>
                    <input type="text" required className="w-full p-2 border rounded bg-white" value={formData.nick} onChange={e => setFormData({...formData, nick: e.target.value})} />
                </div>
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Função (Role)</label>
                    <select className="w-full p-2 border rounded bg-white" value={formData.role} onChange={e => setFormData({...formData, role: e.target.value as UserRole})}>
                        <option value={UserRole.EMPLOYEE}>Funcionário</option>
                        <option value={UserRole.ADMIN}>Admin</option>
                        <option value={UserRole.MASTER}>Master</option>
                    </select>
                </div>
                <div className="pt-4 flex justify-end gap-2">
                    <button type="button" onClick={() => setIsModalOpen(false)} className="px-4 py-2 border rounded">Cancelar</button>
                    <button type="submit" className="px-4 py-2 bg-purple-600 text-white rounded hover:bg-purple-700 flex items-center gap-2">
                        <Save size={16} /> Criar
                    </button>
                </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default Users;
